#@ load("@ytt:data", "data")
---
apiVersion: learningcenter.tanzu.vmware.com/v1beta1
kind: Workshop
metadata:
  name: tap-overview
spec:
  title: TAP Overview
  description: An introduction to the Tanzu Application Platform
  vendor: terasky.com
  difficulty: beginner
  duration: 60m
  url: https://github.com/vrabbi/tap-workshop
  content:
    image: #@ "harbor.{}/tanzu-e2e/eduk8s-tap-workshop:latest".format(data.values.ingress.domain)
    files: #@ "github.com/{}/tap-workshop?ref={}".format(data.values.git.account,data.values.git.branch)
  session:
    resources:
      memory: 3Gi
    env:
      - name: GITEA_PASSWORD
        value: #@ data.values.gitea.adminPassword
      - name: HARBOR_PASSWORD
        value: #@ data.values.harbor.adminPassword
    namespaces:
      budget: custom
    applications:
      terminal:
        enabled: true
        layout: split
      console:
        enabled: true
        vendor: octant
      editor:
        enabled: true
    objects:
    - apiVersion: v1
      kind: LimitRange
      metadata:
        name: resource-limits
      spec:
        limits:
        - max:
            storage: 10Gi
          type: PersistentVolumeClaim
    - apiVersion: e2e.tanzu.vmware.com/v1beta1
      kind: HarborProject
      metadata:
        annotations:
          learningcenter.tanzu.vmware.com/objects.crd.scope: Namespaced
        name: $(session_namespace)
      spec:
        name: $(session_namespace)
    - apiVersion: v1
      data:
        .dockerconfigjson: e30K
      kind: Secret
      metadata:
        annotations:
          secretgen.carvel.dev/image-pull-secret: ""
        name: tap-registry
      type: kubernetes.io/dockerconfigjson
    - apiVersion: v1
      imagePullSecrets:
      - name: registry-credentials
      - name: tap-registry
      kind: ServiceAccount
      metadata:
        name: tap-sa
      secrets:
      - name: registry-credentials
    - apiVersion: rbac.authorization.k8s.io/v1
      kind: Role
      metadata:
        annotations:
          kapp.k14s.io/change-group: role
        name: $(session_namespace)-kapp-permissions
      rules:
      - apiGroups:
        - servicebinding.io
        resources:
        - servicebindings
        verbs:
        - '*'
      - apiGroups:
        - services.tanzu.vmware.com
        resources:
        - resourceclaims
        verbs:
        - '*'
      - apiGroups:
        - serving.knative.dev
        resources:
        - services
        verbs:
        - '*'
      - apiGroups:
        - ""
        resources:
        - configmaps
        verbs:
        - get
        - watch
        - list
        - create
        - update
        - patch
        - delete
    - apiVersion: rbac.authorization.k8s.io/v1
      kind: RoleBinding
      metadata:
        annotations:
          kapp.k14s.io/change-rule: upsert after upserting role
        name: $(session_namespace)-kapp-permissions
      roleRef:
        apiGroup: rbac.authorization.k8s.io
        kind: Role
        name: $(session_namespace)-kapp-permissions
      subjects:
      - kind: ServiceAccount
        name: tap-sa
        namespace: $(session_namespace)
    - apiVersion: rbac.authorization.k8s.io/v1
      kind: ClusterRoleBinding
      metadata:
        name: $(session_namespace)-binding
      roleRef:
        apiGroup: rbac.authorization.k8s.io
        kind: ClusterRole
        name: cluster-admin
      subjects:
      - kind: ServiceAccount
        name: $(service_account)
        namespace: $(workshop_namespace)
    - apiVersion: rbac.authorization.k8s.io/v1
      kind: Role
      metadata:
        name: service-account-role
        namespace: $(session_namespace)
      rules:
      - apiGroups:
        - '*'
        resources:
        - '*'
        verbs:
        - '*'
    - apiVersion: rbac.authorization.k8s.io/v1
      kind: RoleBinding
      metadata:
        annotations:
          kapp.k14s.io/change-rule: upsert after upserting role
        name: $(session_namespace)-service-account-role
      roleRef:
        apiGroup: rbac.authorization.k8s.io
        kind: Role
        name: service-account-role
      subjects:
      - kind: ServiceAccount
        name: default
        namespace: $(session_namespace)
    - apiVersion: v1
      kind: ServiceAccount
      metadata:
        name: app-live-view-connector-service-account
        namespace: $(session_namespace)
    - apiVersion: rbac.authorization.k8s.io/v1
      kind: Role
      metadata:
        name: $(session_namespace)-app-live-view-connector-role
      rules:
      - apiGroups:
        - '*'
        resources:
        - pods
        verbs:
        - watch
    - apiVersion: rbac.authorization.k8s.io/v1
      kind: RoleBinding
      metadata:
        name: $(session_namespace)-app-live-view-connector-role-binding
      roleRef:
        apiGroup: rbac.authorization.k8s.io
        kind: Role
        name: $(session_namespace)-app-live-view-connector-role
      subjects:
      - kind: ServiceAccount
        name: app-live-view-connector-service-account
        namespace: $(session_namespace)
    - apiVersion: apps/v1
      kind: Deployment
      metadata:
        labels:
          app: application-live-view-connector
        name: application-live-view-connector
        namespace: $(session_namespace)
      spec:
        selector:
          matchLabels:
            name: application-live-view-connector
        template:
          metadata:
            labels:
              name: application-live-view-connector
          spec:
            containers:
            - env:
              - name: app.live.view.client.host
                value: application-live-view-7000.app-live-view.svc.cluster.local
              - name: NODE_NAME
                valueFrom:
                  fieldRef:
                    fieldPath: spec.nodeName
              - name: NAMESPACE_NAME
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.namespace
              - name: app.live.view.connector.mode
                value: namespace-scoped
              image: harbor.tap.amer.end2end.link/app-live-view/connector
              imagePullPolicy: IfNotPresent
              livenessProbe:
                httpGet:
                  path: /health
                  port: 8787
                initialDelaySeconds: 15
                periodSeconds: 5
                timeoutSeconds: 3
              name: application-live-view-connector
              resources:
                limits:
                  cpu: 250m
                  memory: 120Mi
                requests:
                  cpu: 150m
                  memory: 70Mi
            serviceAccountName: app-live-view-connector-service-account
